baseURL: https://www.mckendrick.rocks/
languageCode: en-us
title: "My Record Collection"
theme: "PaperMod"
paginate: 10
enableRobotsTXT: true
minify:
  disableXML: true
  minifyOutput: true

UseHugoToc: true
showtoc: true

menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - name: Genres
      url: tags/
      weight: 5

params:
  defaultTheme: dark
  disableThemeToggle: true
  disableSpecial1stPost: true
  profileMode:
    enabled: false
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.3
    minMatchCharLength: 0
    keys: ["tags", "title"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  comments: false
  hidemeta: false

outputs:
  home:
    - HTML
    - RSS
    - JSON
