baseURL = 'https://www.mckendrick.rocks/'
languageCode = 'en-gb'
title = 'McKendrickRocks'
theme = "rocksv2"
paginate = 18
enableRobotsTXT = true

[permalinks]
posts = "/albums/:slug"

[params]
titleBold = "McKendrick"
titleLight = "Rocks"
homeHeader = "Hi, my name is Russ"
homeSubheader = "and this is my record collection, listed in the order I purchased them."
homeButton = "View my collection"

[menu]
[[menu.main]]
name = "Artists"
url = "/artist/"
weight = 20
[[menu.main]]
name = "Styles"
url = "/styles/"
weight = 21
[[menu.main]]
name = "Source Code"
url = "https://github.com/russmckendrick/records"
weight = 22
[[menu.main]]
name = "Genres"
url = "/genres/"
weight = 22
[[menu.end]]
url = "/search/"
identifier = "fa-solid fa-magnifying-glass"
pre = "gray"
weight = 100
[[menu.end]]
url = "/random/"
identifier = "fa-solid fa-shuffle"
pre = "green"
weight = 102
[[menu.footer]]
name = "Source Code"
url = "https://github.com/russmckendrick/records/"
weight = 200
[[menu.footer]]
name = "Random Album"
url = "/random/"
weight = 201

[taxonomies]
artists = "artist"
genres = "genres"
styles = "styles"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]
