[[footer]]
name = "Artist"
url = "/artist"
weight = 10

[[footer]]
name = "Styles"
url = "/styles"
weight = 20

[[footer]]
name = "Genres"
url = "/genres"
weight = 30

[[footer]]
  name = "Random"
  pre = "<i class='bi bi-shuffle'></i>"
  url = "/random/"
  weight = 10
  title = "Grab a random record"
